version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=YourStrongElasticPassword
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/http.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/http.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca.crt
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./certificates/elasticsearch.key:/usr/share/elasticsearch/config/certs/http.key
      - ./certificates/elasticsearch.crt:/usr/share/elasticsearch/config/certs/http.crt
      - ./certificates/elasticsearch.crt:/usr/share/elasticsearch/config/certs/ca.crt
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elastic

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - elastic

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.5.0
    container_name: filebeat
    depends_on:
      - elasticsearch
      - rabbitmq
    volumes:
      - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - rabbitmq_logs:/var/log/rabbitmq:ro
    networks:
      - elastic
    command: ["filebeat", "-e", "-strict.perms=false"]

volumes:
  esdata1:
    driver: local
  rabbitmq_logs:
    driver: local

networks:
  elastic:
    driver: bridge
